### ISSUE TITLE
Ask How to just mount system.img without MBR or GPT inside?

### ISSUE THREAD

**Issue by HadiKhoirudin** [nickdu088/SharpExt4#24]
I'm looking for create file manager R/W with C# for doing some stuff.

I found this source and able to build with VS 2019 .Net Framework 4.8 with some changes like downgrading from Platform Toolset v143 to V142 (VS 2019 default).

Re-create Sample and also DiskPartitionInfo project for change from DotNet SDK into .Net Framework 4.8 version.

Looking into SharpExt4 C++ code and making some changes but I can't just load / mount System.img which not contains MBR or GPT inside.

Any clue or reference for doing this?

Thank you.

**Comment by nickdu088** [comment]
I don't know how your System.img looks like but assume containing the file system only.

Since you don't have entire disk image.
1. You still have to open the disk: https://github.com/nickdu088/SharpExt4/blob/main/Sample/Program.cs#L50
2. Construct your fake partition: https://github.com/nickdu088/SharpExt4/blob/main/Sample/Program.cs#L48
3. Open the disk and partition as normal: https://github.com/nickdu088/SharpExt4/blob/main/Sample/Program.cs#L52

**Comment by HadiKhoirudin** [comment]
Thank you very much this work.

![image](https://github.com/user-attachments/assets/b5d8642d-aa50-45f1-a6bd-04574b766bdf)

**Comment by nickdu088** [comment]
No worries. If you can star the repo, it would be great.
